spring:
  profile.active: dev, test, prod
  datasource:
    url: jdbc:mysql://localhost/topics
    username: root
    password: 0000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:

  error:
    include-stacktrace: never

api:
  security:
    secret: ${JWT_SECRET:123456}